

parameters:

  - name: tags
    displayName: 'Scenarios to run'
    type: string
    default: '@Exito'

################
# job
################
jobs:
  - job:
    displayName: 'JOB: Execute API Tests'
    continueOnError: false
    timeoutInMinutes: 30


    pool: # agent pool
      vmImage: windows-latest

    steps:

      ## example using Maven
      - task: Maven@3
        displayName: 'Run Test'
        continueOnError: true
        timeoutInMinutes: 20
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean verify -Dcucumber.filter.tags=${{ parameters.tags }}'
          publishJUnitResults: false
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          mavenVersionOption: 'Default'
          mavenSetM2Home: false
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

