trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'

  - script: |
      mvn -B clean install
    displayName: 'Build and Test with Maven'